import React from "react";

import { Form, useActionData, redirect } from "react-router-dom";
import api from "../../api/axios";
import useAuth from "../../hooks/useAuth";

export default function CreatePost() {
  // The useActionData() hook allows us access to the return data
  // from the createPostAction() below.
  // We can use it to inform any form updates/responses here.
  const { auth } = useAuth();
  const data = useActionData();
  return (
    <div className="contact">
      <h3>Create Blog Post</h3>
      <Form method="post" action="/createpost">
        <label>
          <span>Title:</span>
          <input type="message" name="title" required />
        </label>
        <label>
          <span>Your post:</span>
          <textarea type="message" name="content" required></textarea>
        </label>
        <button>Create Post</button>
        {/* Check if the data from the createPostAction() below returned an error
          If so, show the user. */}
        {data && data.error && <p>{data.error}</p>}
      </Form>
    </div>
  );
}

/**
 * Handler for form data above.
 * @param {request} Contains the form data.
 * @returns
 */
export const createPostAction =
  ({ auth }) =>
  async ({ request }) => {
    // Pre-condition: User is logged in
    //  console.log(request);
    try {
      // Build the new blog post
      const data = await request.formData();
      //      console.log("createPostAction> data: ");
      //      console.log(data);
      const userName = auth.userName;
      console.log("createPostAction> userName: " + userName);
      const newPost = {
        //    id: auto generated by mongodb
        author: userName,
        modifieddate: new Date().toLocaleString(),
        title: data.get("title"),
        content: data.get("content"),
      };
      //    console.log("contactAction> newPostData: " + JSON.stringify(newPost));

      // Next, submit the new post
      await api.post("/blogposts", newPost);
    } catch (err) {
      if (err.response) {
        // Not in the 200 response range
        console.log(err.response.data);
        console.log(err.response.status);
        console.log(err.response.headers);
      } else {
        // No response or non-200 error
        console.log(`createPostAction> Error: ${err.message}`);
      }
    }

    // redirect the user
    return redirect("/");
  };
